title:            Novay Notes
description:      Just a nonsense freelancer who've been always loving to be a freelance developer<br/> actually it let me be kept in the process of learning a new think. 
url:              http://localhost:4000
logo:             site-logo.png
disqus_shortname: novaynotes
search:           true

owner:
  name:           Noviyanto Rachmady
  avatar:         avatar.jpeg
  email:          novay@otaku.si
  twitter:        novaymawbowo        
  facebook:       novaymawbowo      
  github:         novay        
  stackexchange:  novay
  tumblr:         novay
  soundcloud:     novay
  google_plus:    novaymawbowo

google_analytics: UA-47779092-1 
google_verify:    miCVO93n3KnkRmWe_kgLGdeJyowTdI6kSJI4-7qFQA4
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:      7C34C63C60FFD8CCC9BBC577761AD928   

# Links to include in top navigation
# For external links add external: true
links:
  - title: <i class="icon-home"></i> Home
    url: /
  - title: <i class="icon-tags"></i> Blog
    url: /blog/
  - title: <i class="icon-archive"></i> Resume
    url: /resume/
  - title: <i class="icon-map-marker"></i> Contact
    url: /kontak/

timezone:    Asia/Makassar
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:day/:title/

relative_permalinks: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess", "_pages"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
